# version: "3.9"
 
# services:
#   web:
#     build: .
#     command: gunicorn BackPage.wsgi:application --bind 0.0.0.0:9000 --workers 3
#     volumes:
#       - .:/app
#       - /var/www/ropeace/static:/app/staticfiles
#       - /var/www/ropeace/media:/app/media
#     env_file:
#       - .env
#     environment:
#       CELERY_BROKER_URL: redis://redis:6379/0
#       CELERY_RESULT_BACKEND: redis://redis:6379/0
#     ports:
#       - "9000:9000"
#     depends_on:
#       - redis
 
#   worker:
#     build: .
#     command: celery -A BackPage worker -l info
#     volumes:
#       - .:/app
#     env_file:
#       - .env
#     environment:
#       CELERY_BROKER_URL: redis://redis:6379/0
#       CELERY_RESULT_BACKEND: redis://redis:6379/0
#     depends_on:
#       - redis
#       - web
 
#   redis:
#     image: redis:alpine




version: "3.9"

services:
  web:
    build: .
    command: gunicorn BackPage.wsgi:application --bind 0.0.0.0:9000 --workers 3 --timeout 300
    env_file:
      - .env
    volumes:
      - .:/app
      - /var/www/ropeace/static:/app/staticfiles
      - /var/www/ropeace/media:/app/media
      - ./cookies.txt:/cookies.txt

    ports:
      - "9000:9000"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A BackPage worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
      - /var/www/ropeace/static:/app/staticfiles
      - /var/www/ropeace/media:/app/media
      - ./cookies.txt:/cookies.txt

    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  postgres_data:
